export const ASSISTANT_CHAT_REQUEST = 'ASSISTANT_CHAT_REQUEST'
export const ASSISTANT_CHAT_SUCCESS = 'ASSISTANT_CHAT_SUCCESS'
export const ASSISTANT_CHAT_FAIL = 'ASSISTANT_CHAT_FAIL'

export const CHATLOG_LIST_REQUEST = 'CHATLOG_LIST_REQUEST'
export const CHATLOG_LIST_SUCCESS = 'CHATLOG_LIST_SUCCESS'
export const CHATLOG_LIST_FAIL = 'CHATLOG_LIST_FAIL'
