export const FEATURE_LIST_REQUEST = 'FEATURE_LIST_REQUEST'
export const FEATURE_LIST_SUCCESS = 'FEATURE_LIST_SUCCESS'
export const FEATURE_LIST_FAIL = 'FEATURE_LIST_FAIL'

export const FEATURE_TOGGLE = 'FEATURE_TOGGLE'
export const FEATURE_TRAFFIC_UPDATE = 'FEATURE_TRAFFIC_UPDATE'
