export const FEATURE_LIST_REQUEST = 'FEATURE_LIST_REQUEST'
export const FEATURE_LIST_SUCCESS = 'FEATURE_LIST_SUCCESS'
export const FEATURE_LIST_FAIL = 'FEATURE_LIST_FAIL'

export const FEATURE_UPDATE_REQUEST = 'FEATURE_UPDATE_REQUEST'
export const FEATURE_UPDATE_SUCCESS = 'FEATURE_UPDATE_SUCCESS'
export const FEATURE_UPDATE_FAIL = 'FEATURE_UPDATE_FAIL'
